# Generated by Django 5.1.4 on 2024-12-12 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=500)),
                ('attachment', models.FileField(upload_to='email-attachments')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.list')),
            ],
        ),
    ]
