# Generated by Django 5.1.4 on 2024-12-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('gpa', models.CharField(blank=True, max_length=4, null=True)),
                ('graduation_year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
